@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity color_point_rgb_with_unit_interval {
  .. meta ..
  id : uuid ⚡
  lock_version : integer
  created_at : timestamp_utc_usec ⚡
  created_by : url ⚡
  updated_at : timestamp_utc_usec ⚡
  updated_by : url ⚡
  deleted_at : timestamp_utc_usec ⚡
  deleted_by : url ⚡
  locale_code : string ⚡
  tagging : string ⚡
  .. Main ..
  red : unit_interval
  green : unit_interval
  blue : unit_interval
}

@enduml
