@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity postal_contact {
  freeform : text
  country_id : country(id)
  country_subdivision_id : country_subdivision(id)
  district_text : string
  locality_id : locality(id)
  locality_division_id : locality_division(id)
  neighborhood_text : string
  postal_code_text : string
  street_address_text : string
  premise_address_text : string
  global_location_number_text : string
}

@enduml
