@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity passport {
  .. meta ..
  id : uuid ⚡
  lock_version : integer
  created_at : timestamp_utc_usec ⚡
  created_by : url ⚡
  updated_at : timestamp_utc_usec ⚡
  updated_by : url ⚡
  retired_at : timestamp_utc_usec ⚡
  retired_by : url ⚡
  locale_code : string ⚡
  tagging : string ⚡
  .. card ..
  name : string(50) ⚡
  subname : string(50) ⚡
  summary : string(72)
  description : text
  disambiguation : text
  sign : string(1) ⚡
  kind : string ⚡
  avatar_image_400x400_url : url
  avatar_image_400x400_alt : url
  main_image_1080x1080_url : url
  main_image_1080x1080_alt : text
  main_image_1920x1080_url : url
  main_image_1920x1080_alt : text
  main_image_1080x1920_url : url
  main_image_1080x1920_alt : text
  emoji : text
  star_count : integer
  quick_response_code_id : quick_response_code.id 🔑
  universal_product_code_id : universal_product_code.id 🔑
  .. ICAO 9303 DG1 required personal details ..
  name_of_holder : text
  nationality : text
  date_of_birth : date
  date_of_birth_check_digit : int
  sex : text
  composite_check_digit : int
  .. ICAO 9303 DG1 required document details ..
  document_type : text
  document_number : text
  document_number_check_digit : int
  issuing_state_or_organization : text
  date_of_expiry_or_valid_until_date : date
  date_of_expiry_or_valid_until_date_check_digit : int
  optional_data : text
  optional_data_check_digit : int
  .. ICAO 9303 DG2 ..
  encoded_face : binary
  .. ICAO 9303 DG3 ..
  encoded_fingers : binary
  .. ICAO 9303 DG4 ..
  encoded_eyes : binary
  .. ICAO 9303 DG5 ..
  displayed_portrait : binary
  .. ICAO 9303 DG6 ..
  reserved_for_future_use : todo
  .. ICAO 9303 DG7 ..
  displayed_signature_or_usual_mark : binary
  .. ICAO 9303 DG8 ..
  data_features : unknown
  .. ICAO 9303 DG9 ..
  structure_features : unknown
  .. ICAO 9303 DG10 ..
  substance_features : todo
  .. ICAO 9303 DG11 additional personal details ..
  other_names_of_holder : text
  place_of_birth : text
  personal_number : text
  address : text
  telephone_numbers : text
  profession : text
  title : text
  personal_summary : text
  proof_of_citizenship : text
  other_valid_travel_documents : text
  custody_information : text
  .. ICAO 9303 DG12 additional document details ..
  issuing_authority : text
  date_of_issue : date
  other_persons_included_on_mrtd : text
  endorsements_observations : text
  tax_exit_requirements : text
  image_of_front_of_mrtd : binary
  image_of_rear_of_mrtd : binary
  .. ICAO 9303 DG13 ..
  optional_details : text
  .. ICAO 9303 DG14 ..
  security_options : todo
  .. ICAO 9303 DG15 ..
  active_authentication_public_key_info : todo
  .. ICAO 9303 DG16 ..
  persons_to_notify : text
  contact_details_of_persons_to_notify : text
  .. Extra ..
  country_id : country.id 🔑
  four_corner_open_book_photo_url : url
  four_corner_clear_face_open_book_photo_url : url
}

@enduml
