@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity portal {
    key : string+
}

entity portal_locale {
    portal : portal(id)+
    locale : locale(id)+
    name : string+
    summary : string
    description : text
}

portal ||-r-o{ portal_locale

@enduml
