@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

' a.k.a. color using RGBA-32
entity color_point_rgba_with_byte {
  red : byte
  green : byte
  blue : byte
  alpha : byte
}

@enduml
