@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity email_contact {
  address : text
  display_name : text
  local_part : text
  domain : text
  addr_spec : text
}

@enduml
