@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity feed {
    key : string+
}

entity feed_locale {
    feed : feed(id)+
    locale : locale(id)+
    name : string+
    summary : string
    description : text
    disambiguation : text
}

feed ||-r-o{ feed_locale

@enduml
