@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity thing {
    key : string+
}

entity thing_locale {
    thing : thing(id)+
    locale : locale(id)+
    name : string+
    summary : string
    description : text
}

thing ||-r-o{ thing_locale

@enduml
