@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity color_point_cymk_as_unit_interval {
  .. Meta ..
  id : uuid ⚡
  sign : char ⚡
  lock_version : integer
  created_at : timestamp_utc_usec ⚡
  created_by : url ⚡
  updated_at : timestamp_utc_usec ⚡
  updated_by : url ⚡
  deleted_at : timestamp_utc_usec ⚡
  deleted_by : url ⚡
  locale_code : string ⚡
  .. Main ..
  cyan : unit_interval
  yellow : unit_interval
  magenta : unit_interval
  black : unit_interval
}

@enduml
