@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity ability {
    key : string
}

entity ability_locale {
    ability : ability(id)
    locale : locale(id)
    name : string+
    summary : string
    description : text
}

ability ||-r-o{ ability_locale

@enduml
