@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity access_operation {
    key : string
}

entity access_operation_locale {
    access_operation : access_operation(id)
    locale : locale(id)
    name : string+
    summary : string+
    description : text
}

access_operation -r-o{ access_operation_locale

@enduml
