@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity geography_point {
  .. Meta ..
  id : bigint ⚡
  zid : uuid ⚡
  lock_version : int
  created_at : timestamp
  created_by : url
  updated_at : timestamp
  updated_by : url
  retired_at : timestamp
  retired_by : url
  locale_id : locale.id 🔑
  .. Main ..
  latitude_as_decimal_degrees : decimal_degrees
  longitude_as_decimal_degrees : decimal_degrees
  altitude_agl_as_meters : meters
  altitude_msl_as_meters : meters
  elevation_agl_as_meters : meters
  elevation_msl_as_meters : meters
}

@enduml
