@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity license_type {
    key : string+
}

entity license_type_locale {
    license_type : license_type(id)+
    locale : locale(id)+
    name : string+
    summary : string
    description : text
    disambiguation : text
}

license_type ||-r-o{ license_type_locale

@enduml
