@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity meta {
  .. Meta ..
  id : uuid ⚡
  sign : char
  lock_version : integer
  created_at : timestamp_utc_usec
  created_by : url
  updated_at : timestamp_utc_usec
  updated_by : url
  retired_at : timestamp_utc_usec
  retired_by : url
  locale_id : locale.id 🔑
}

@enduml
