@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity pantone_process_color {
  .. Meta ..
  id : uuid ⚡
  sign : string ⚡
  lock_version : integer
  created_at : timestamp ⚡
  created_by : url ⚡
  updated_at : timestamp ⚡
  updated_by : url ⚡
  deleted_at : timestamp ⚡
  deleted_by : url ⚡
  locale_id : locale.id ⚡ 🔑
  .. Main ..
  key : string ⚡
  name : string ⚡
  code : string ⚡
  stock : string ⚡
}

@enduml
