@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity pantone_process_color {
  .. Meta ..
  id : uuid ⚡
  lock_version : int
  created_at : timestamp
  created_by : url
  updated_at : timestamp
  updated_by : url
  retired_at : timestamp
  retired_by : url
  locale_id : locale.id 🔑
  .. Main ..
  key : string ⚡
  name : string ⚡
  code : string(3) ⚡
  stock : string(1) ⚡
}

@enduml
