@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

package ColorPoint {
  entity color_point_kit
  entity color_point_rgb_with_byte
  entity color_point_rgb_with_unit_interval
  entity color_point_rgba_with_byte
  entity color_point_rgba_with_unit_interval
  entity color_point_cymk_with_byte
  entity color_point_cymk_with_unit_interval
  entity color_point_cymka_with_byte
  entity color_point_cymka_with_unit_interval
}

@enduml
