@startuml uml
skinparam monochrome true

entity course {
    key : string
}

entity course_locale {
    course : course(id)
    locale : locale(id)
    name : string
    summary : string
    description : text
}

@enduml
