@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity color_name_kit {
  .. meta ..
  id : uuid ⚡
  lock_version : integer
  created_at : timestamp_utc_usec ⚡
  created_by : url ⚡
  updated_at : timestamp_utc_usec ⚡
  updated_by : url ⚡
  deleted_at : timestamp_utc_usec ⚡
  deleted_by : url ⚡
  locale_code : string ⚡
  tagging : string ⚡
  .. Main ..
  hex : hexdigit(6)+
  html_color_name : text
  x11_color_name : text
  color_naming_system_name : text
  pantone_process_color_name : text
}

@enduml
