@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity color_name_kit {
  .. Meta ..
  id : uuid ⚡
  sign : char ⚡
  lock_version : integer
  created_at : timestamp ⚡
  created_by : url ⚡
  updated_at : timestamp ⚡
  updated_by : url ⚡
  deleted_at : timestamp ⚡
  deleted_by : url ⚡
  locale_id : locale.id ⚡ 🔑
  .. Main ..
  hex : hexdigit
  html_color_name : text
  x11_color_name : text
  color_naming_system_name : text
  pantone_process_color_name : text
}

@enduml
