@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity topic {
    key : string+
}

entity topic_locale {
    topic : topic(id)+
    locale : locale(id)+
    name : string+
    summary : string
    description : text
    disambiguation : text
}

topic ||-r-o{ topic_locale

@enduml
