@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity united_kingdom_standard_occupational_classification_2020 {
  .. Main ..
  code : string ⚡
  title : string ⚡
  definition : string
}

@enduml
