@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity message {
    key : string+
}

entity message_locale {
    message : message(id)+
    locale : locale(id)+
    name : string+
    summary : string
    description : text
    disambiguation : text
}

message ||-r-o{ message_locale

@enduml
