@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity measurement_unit {
  .. meta ..
  id : uuid ⚡
  lock_version : integer
  created_at : timestamp_utc_usec ⚡
  created_by : url ⚡
  updated_at : timestamp_utc_usec ⚡
  updated_by : url ⚡
  retired_at : timestamp_utc_usec ⚡
  retired_by : url ⚡
  locale_code : string ⚡
  tagging : string ⚡
  .. Main ..
  name : text
  symbol : text
  measurement_system_id : measurement_system.id 🔑
  .. Ratio ..
  numerator : measurement_unit.id
  denominator : measurement_unit.id
}

@enduml
