@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity color_point_cymk_with_unit_interval {
  cyan : unit_interval
  yellow : unit_interval
  magenta : unit_interval
  black : unit_interval
}

@enduml
