@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity content_image {
  name : string+
  codec_id : codec(id)+
  width_as_pixels : count
  height_as_pixels : count
}

@enduml
