@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity software_package_data_exchange_license {
  .. Meta ..
  id : uuid ⚡
  sign : char ⚡
  lock_version : integer
  created_at : timestamp_utc_usec ⚡
  created_by : url ⚡
  updated_at : timestamp_utc_usec ⚡
  updated_by : url ⚡
  deleted_at : timestamp_utc_usec ⚡
  deleted_by : url ⚡
  locale_id : locale.id ⚡ 🔑
  .. Main ..
  code : string ⚡
}

@enduml
