@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity locale {
  text : text
  language_code : string
  country_code : string
  script_code : string
  region_code : string
  variant_code : string
  __separators__
  decimal_separator : text
  grouping_separator : text
  __currency__
  currency_code : string
  currency_symbol : string
  __quotation__
  quotation_start_delimiter : text
  quotation_stop_delimiter : text
  __characters__
  collator_identifier : text
  collation_identifier : text
  exemplar_character_set : character set
  __systems__
  calendar_system_id : calendar_system(id)+
  measurement_system_id : measurement_system(id)+
}

@enduml
