@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity plan_okr {
  .. Meta ..
  id : uuid ⚡
  lock_version : integer
  created_at : timestamp
  created_by : url
  updated_at : timestamp
  updated_by : url
  retired_at : timestamp
  retired_by : url
  locale_id : locale.id 🔑
  .. Card ..
  title : string ⚡
  subtitle : string ⚡
  summary : string
  description : text
  disambiguation : text
  avatar_image_400x400_url : url
  avatar_image_400x400_alt : url
  main_image_1080x1080_url : url
  main_image_1080x1080_alt : text
  main_image_1920x1080_url : url
  main_image_1920x1080_alt : text
  main_image_1080x1920_url : url
  main_image_1080x1920_alt : text
  emoji : text
  star_count : integer
  quick_response_code_id : quick_response_code.id 🔑
  universal_product_code_id : universal_product_code.id 🔑
  .. Main ..
  plan_id : plan.id 🔑
  objective_card_id : card.id 🔑
  key_result_card_ids : card.id[]
}

@enduml
