@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity color_point_cymka_with_unit_interval {
  .. Meta ..
  id : uuid ⚡
  sign : string ⚡
  lock_version : integer
  created_at : timestamp ⚡
  created_by : url ⚡
  updated_at : timestamp ⚡
  updated_by : url ⚡
  deleted_at : timestamp ⚡
  deleted_by : url ⚡
  locale_id : locale.id ⚡ 🔑
  .. Main ..
  cyan : unit_interval
  yellow : unit_interval
  magenta : unit_interval
  black : unit_interval
  alpha : unit_interval
}

@enduml
