@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity color_point_cymka_with_unit_interval {
  .. Meta ..
  id : uuid ⚡
  lock_version : int
  created_at : timestamp
  created_by : url
  updated_at : timestamp
  updated_by : url
  retired_at : timestamp
  retired_by : url
  locale_id : locale.id 🔑
  .. Main ..
  cyan : unit_interval
  yellow : unit_interval
  magenta : unit_interval
  black : unit_interval
  alpha : unit_interval
}

@enduml
