@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity person {
    born_date : date+
    born_year : integer+
    died_date : date+
    died_year : integer+
}

entity person_locale {
    person_id : person(id)
    locale_id : locale(id)
    __ main naming __
    given_naming : text
    given_naming_phonetic : text
    middle_naming : text
    middle_naming_phonetic : text
    family_naming : text
    family_naming_phonetic : text
    legal_naming : text
    legal_naming_phonetic : text
    formal_naming : text
    formal_naming_phonetic : text
    __ adjunct naming __
    prefix_naming : text
    prefix_naming_phonetic : text
    suffix_naming : text
    suffix_naming_phonetic : text
    salutation_naming : text
    salutation_naming_phonetic : text
    addressee_naming : text
    addressee_naming_phonetic : text
    nicknames : text[]
    __ pronouns __
    subject_pronoun : text
    object_pronoun : text
    dependent_possessive_pronoun : text
    independent_possessive_pronoun : text
    reflexive_pronoun : text
    intensive_pronoun : text
    disjunctive_pronoun : text
}

person -r-o{ person_locale

@enduml
