@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity codec {
  .. Meta ..
  id : uuid ⚡
  lock_version : integer
  created_at : timestamp
  created_by : url
  updated_at : timestamp
  updated_by : url
  retired_at : timestamp
  retired_by : url
  locale_id : locale.id 🔑
  .. Card ..
  title : string(50) ⚡
  subtitle : string(50) ⚡
  summary : string
  description : text
  disambiguation : text
  image_1080x1080_url : url
  image_1080x1080_alt : text
  emoji : text
  star_count : integer
  .. Main ..
  name : text
  code : text
  icon : text
  link : text
  note : text
  creator_name : text
  prefer_file_extension : text
  prefer_media_type_id : media_type.id 🔑
  lossy_flag : boolean
  floss_flag : boolean
  .. Bit Rate ..
  fixed_bit_rate : decimal
  variable_bit_rate_minimum : decimal
  variable_bit_rate_maximum : decimal
  .. Channel Count ..
  fixed_channel_count : integer
  variable_channel_count_minimum : integer
  variable_channel_count_maximum : integer
}

@enduml
