#!/bin/sh

# Process a plantuml class file to a Ruby on Rails generator scaffold.
#
# Example:
#
#     cat tables.plantuml | plantuml-class-to-rails-scaffold
#
gsed "s/^'''.*/###/; s/^'/#/;" |
gsed 's/^class \(\w\+\) .*/rails generate scaffold \1 \\/; s/^}.*//;' |
gsed 's/^  \(\w\+\) text/  \1:string \\/;' |
gsed 's/^  \(\w\+\) numeric/  \1:int \\/;'
