#!/bin/sh

# Process a plantuml class file to markdown text.
#
# Example:
#
#     cat tables.plantuml | plantuml-class-to-markdown
#
grep '^\(package\|  class\) ' |
sed 's/^package \([_[:alnum:]]\{1,\}\) *{ */⏎\1:⏎/; s/^[[:space:]]*class \([_[:alnum:]]\{1,\}\)/* [\1](concepts\/\1.md)/;' | 
tr '⏎' '\n'
