@startuml all

' use monochrome instead of color
skinparam monochrome true
skinparam linetype ortho
hide circle

' use orthogonal lines to fix problems with angled crows feet
skinparam linetype ortho

' hide the spot
hide circle

'left to right direction
top to bottom direction

' transparent layout box
skinparam package<<Layout>> {
  borderColor Transparent
  backgroundColor Transparent
  fontColor Transparent
  stereotypeFontColor Transparent
}

'''
'
' Package section
'
'''

package Graph {
  entity node
  entity edge
}

package Base {
  entity note
  entity role
  entity group
  entity trait
}

package Data {
  entity unit
  entity tag
  entity pair
  entity note
  entity codec
  entity locale
  entity calendar_system
  entity measurement_system
  entity media_type
  entity microdata_item
  entity currency
  entity license_type
}

package Content {
  entity content_application
  entity content_audio
  entity content_font
  entity content_example
  entity content_image
  entity content_message
  entity content_model
  entity content_multipart
  entity content_text
  entity content_video
}

package Color {
  entity color_point_kit
  entity color_point_rgb_with_byte
  entity color_point_rgb_with_unit_interval
  entity color_point_rgba_with_byte
  entity color_point_rgba_with_unit_interval
  entity color_point_cymk_with_byte
  entity color_point_cymk_with_unit_interval
  entity color_point_cymka_with_byte
  entity color_point_cymka_with_unit_interval
}

package Geo {
  entity geography_point
  entity geography_point_code
  entity geography_point_center
}

package Contact {
  entity uri_contact
  entity email_contact
  entity phone_contact
  entity postal_contact
}

package Social {
  entity post
  entity feed
  entity page
  entity room
  entity role
  entity group
  entity topic
  entity portal
  entity message
  entity notification
}

package Concept {
  entity person
  entity person_locale
  entity place
  entity place_locale
  entity thing
  entity thing_locale
  entity event
  entity event_locale
  entity artist
  entity album
  entity song
  entity book
  entity when
  entity job_opening
  entity movie
  entity offer
  entity organization
  entity sport
  entity travel
}

package Plan {
  entity plan_budget
  entity plan_milestone
  entity plan_output
  entity plan_outcome
  entity plan_impact
  entity plan_objective
  entity plan_result
  entity plan_metric
  entity plan_gist
  entity plan_gist_goal
  entity plan_gist_idea
  entity plan_gist_step
  entity plan_gist_task
  entity plan_smart
  entity plan_smart_specific
  entity plan_smart_measurable
  entity plan_smart_actionable
  entity plan_smart_relevant
  entity plan_smart_timely
  entity plan_rice
  entity plan_rice_reach
  entity plan_rice_impact
  entity plan_rice_confidence
  entity plan_rice_effort
  entity plan_rope
  entity plan_rope_realistic
  entity plan_rope_optimistic
  entity plan_rope_pessimistic
  entity plan_rope_equilibristic
}

package Code {
  entity international_standard_classification_occupations_2008
  entity united_states_bureau_of_labor_statistics_standard_occupational_classification_2018
}

'''
'
' Graph
'
'''

entity node {
  uri : text
  text : text
  jsonb : jsonb
  xml : xml
  number : numeric
}

entity edge {
__ Subject __
  subject_uri : text
  subject_database : text
  subject_schema : text
  subject_table : text
  subject_id : subject(id)+
__ Predicate __
  predicate_uri : text
  predicate_database : text
  predicate_schema : text
  predicate_table : text
  predicate_id : predicate(id)+
__ Object __
  object_uri : text
  object_database : text
  object_schema : text
  object_table : text
  object_id : object(id)+
__ Lifecycle __
  start_at_timestamp_utc : timestamp
  stop_at_timestamp_utc : timestamp
__ Modifiers __
  count : integer
  weight : decimal
  probability : unit_interval
  confidence : unit_interval
  multiplier_unit_interval : unit_interval
  multiplier_dual_interval : dual_interval
}

'''
'
' Base
'
'''

entity note {
  name : string+
  summary : string
  description : text
  disambiguation : text
}

entity role {
  name : string+
  summary : string
  description : text
  disambiguation : text
}

entity group {
  name : string+
  summary : string
  description : text
  disambiguation : text
}

entity trait {
  name : string+
  summary : string
  description : text
  disambiguation : text
}

'''
'
' Access
'
'''

package Access {
  entity access_tenant
  entity access_tenant_locale
  entity access_occupancy
  entity access_agent
  entity access_agent_locale
  entity access_assignment
  entity access_attribute
  entity access_attribute_locale
  entity access_permission
  entity access_operation
  entity access_operation_locale
}

entity access_tenant {
}

entity access_tenant_locale {
  name : string+
  summary : string
  description : text
  disambiguation : text
}

entity access_occupancy {
  access_tenant_id : access_tenant(id)+
  access_agent_id : access_agent(id)+
}

entity access_agent {
}

entity access_agent_locale {
  name : string+
  summary : string
  description : text
  disambiguation : text
}

entity access_assignment {
  access_agent_id : access_agent(id)+
  access_attribute_id : access_attribute(id)+
}

entity access_attribute {
}

entity access_attribute_locale {
  name : string+
  summary : string
  description : text
  disambiguation : text
}

entity access_permission {
  access_attribute : id
  access_operation_id : access_operation(id)+
}

entity access_operation {
}

entity access_operation_locale {
  name : string+
  summary : string
  description : text
  disambiguation : text
}

'''
'
' System
'
'''

package System {
  entity system_user
  entity system_group
  entity system_path
  entity system_proc
  entity system_env
}

entity system_user {
  uid : integer
  name : string+
}

entity system_group {
  gid : integer
  name : string+
}

entity system_path {
  iid : integer
  name : string+
}

entity system_proc {
  pid : integer
  name : string+
}

entity system_env {
  key : string+
  value : text
}

'''
'
' Data
'
'''

entity unit {
  name : string+
  symbol : string
}

entity tag {
  text : text
  summary : string
  description : text
  disambiguation : text
}

entity locale {
  text : text
  language_code : string
  country_code : string
  script_code : string
  region_code : string
  variant_code : string
  decimal_separator : text
  grouping_separator : text
  currency_code : string
  currency_symbol : string
  quotation_start_delimiter : text
  quotation_stop_delimiter : text
  collator_identifier : text
  collation_identifier : text
  exemplar_character_set : character set
  calendar_system_id : calendar_system(id)+
  measurement_system_id : measurement_system(id)+
}

entity calendar_system {
  name : string+
}

entity measurement_system {
  name : string+
}

entity codec {
  name : string+
  code : string
  icon : text
  link : text
  note : text
  creator_name : string+
  prefer_file_extension : text
  prefer_media_type_id : prefer_media_type(id)+
  lossy_flag : boolean
  floss_flag : boolean
  fixed_bit_rate : decimal
  variable_bit_rate_minimum : decimal
  variable_bit_rate_maximum : decimal
  fixed_channel_count : integer
  variable_channel_count_minimum : integer
  variable_channel_count_maximum integer
}

entity media_type {
  text : text
  supertype : string
  subtype : string
  tree : string
  suffix  : string
  parameters : string[]
}

entity microdata_item {
  itemtype : string
  itemprop : string
}

entity currency {
  name : string+
  code : string
  symbol : string
}

entity license_type {
  name : string+
  spdx_identifier : string
  text : text
}

'''
'
' Content
'
'''

entity content_application {
  name : string+
}

entity content_audio {
  name : string+
  codec_id
  duration_as_seconds count
}

entity content_font {
  name : string+
}

entity content_example {
  name : string+
}

entity content_image {
  name : string+
  codec_id
  width_as_pixels count
  height_as_pixels count
}

entity content_message {
  name : string+
}

entity content_model {
  name : string+
}

entity content_multipart {
  name : string+
}

entity content_text {
  name : string+
}

entity content_video {
  name : string+
  codec_id
  duration_as_seconds count
}

'''
'
' Color
'
'''

entity color_point_kit {
  hex : string+
  color_point_id : color_point(id)+
  html_color_name : string+
  x11_color_name : string+
  color_naming_system_name : string+
  pantone_color_name : string+
}

' a.k.a. RGB-24
entity color_point_rgb_with_byte {
  red : byte
  green : byte
  blue : byte
}

entity color_point_rgb_with_unit_interval {
  red : unit_interval
  green : unit_interval
  blue : unit_interval
}

' a.k.a. RGBA-32
entity color_point_rgba_with_byte {
  red : byte
  green : byte
  blue : byte
  alpha : byte
}

entity color_point_rgba_with_unit_interval {
  red : unit_interval
  green : unit_interval
  blue : unit_interval
  alpha : unit_interval
}

entity color_point_cymk_with_byte {
  cyan : byte
  yellow : byte
  magenta : byte
  black : byte
}

entity color_point_cymk_with_unit_interval {
  cyan : unit_interval
  yellow : unit_interval
  magenta : unit_interval
  black : unit_interval
}

entity color_point_cymka_with_byte {
  cyan : byte
  yellow : byte
  magenta : byte
  black : byte
  alpha : byte
}

entity color_point_cymka_with_unit_interval {
  cyan : unit_interval
  yellow : unit_interval
  magenta : unit_interval
  black : unit_interval
  alpha : unit_interval
}

'''
'
' Geo
'
'''

entity geography_point {
  latitude : numeric
  longitude : numeric
  altitude : numeric
  elevation : numeric
}

entity geography_point_code {
  geography_point_id : text
  name : string+
}

entity geography_point_center {
  geography_point_id : geography_point(id)+
  spread_as_meters : numeric
}

'''
'
' Contact
'
'''

entity uri_contact {
  label : text
  uri : text
}

entity email_contact {
  label : text
  address : text
  display_name : string+
  addr_spec : text
}

entity phone_contact {
  label : text
  number_text : text
  e164_text : text
  e164_country_code : string
  e164_national_destination_code : string
  e164_group_identification_code : string
  e164_trial_identification_code : string
  e164_subscriber_number : text
}

entity postal_contact {
  label : text
  country_text : text
  region_text : text
  district_text : text
  locality_text : text
  locality_division_text : text
  neighborhood_text : text
  postal_code_text : text
  street_address_text : text
  premise_address_text : text
  global_location_number_text : text
}

entity passport_credential {
  label : text
  country_text : text
  number_text : text
  valid_start_date : date
  valid_stop_date : date
}

'''
'
' Personal
'
'''

entity person {
  name : string+
  summary : string
  description : text
  disambiguation : text
}

entity person_locale {
  person_id : person(id)+
  locale_id : locale(id)+
  __ naming __
  given_naming : text
  middle_naming : text
  family_naming : text
  legal_naming : text
  formal_naming : text
  prefix_naming : text
  suffix_naming : text
  salutation_naming : text
  addressee_naming : text
  nicknames : text[]
  __ pronoun __
  subject_pronoun : text
  object_pronoun : text
  dependent_possessive_pronoun : text
  independent_possessive_pronoun : text
  reflexive_pronoun : text
  intensive_pronoun : text
  disjunctive_pronoun : text
}

'''
'
' Social
'
'''

entity post {
  name : string+
  summary : string
  description : text
  disambiguation : text
}

entity feed {
  name : string+
  summary : string
  description : text
  disambiguation : text
}

entity page {
  name : string+
  summary : string
  description : text
  disambiguation : text
}

entity room {
  name : string+
  summary : string
  description : text
  disambiguation : text
}

entity role {
  name : string+
  summary : string
  description : text
  disambiguation : text
}

entity group {
  name : string+
  summary : string
  description : text
  disambiguation : text
}

entity topic {
  name : string+
  summary : string
  description : text
  disambiguation : text
}

entity portal {
  name : string+
  summary : string
  description : text
  disambiguation : text
}

entity message {
  name : string+
  summary : string
  description : text
  disambiguation : text
}

entity notification {
  name : string+
  summary : string
  description : text
  disambiguation : text
}

'''
'
' Concept
'
'''

entity place {
}

entity place_locale {
  place_id : place(id)+
  locale_id : locale(id)+
  name : string+
  summary : string
  description : text
  disambiguation : text
}

entity thing {
}

entity thing_locale {
  thing_id : thing(id)+
  locale_id : locale(id)+
  summary : string
  description : text
  disambiguation : text
  disambiguating_description : text
}

entity event {
  who_as_group_id_list id[]
  what_as_thing_id_list id[]
  where_as_place_id_list id[]
  when_as_date_time_range_list id[]
}

entity event_locale {
  event_id : event(id)+
  locale_id : locale(id)+
  name : string+
  summary : string
  description : text
  disambiguation : text
}

entity when {
  year : number
  month : number
  monthday : number
  recurring : TODO
}

entity artist {
  name : string+
}

entity album {
  name : string+
}

entity song {
  name : string+
}

entity book {
  name : string+
}

entity movie {
  name : string+
}

entity sport {
  name : string+
}

entity travel {
  name : string+
}

'''
'
' Plan
'
'''

entity plan_objective {
  name : string+
  metric_id : text
}

entity plan_result {
  name : string+
  metric_id : text
}

entity plan_metric {
  name : string+
  value : numeric
}

entity plan_gist {
  goal_id
  idea_id
  step_id
  task_id
}

entity plan_gist_goal {
  name : string+
  summary : string
  description : text
  disambiguation : text
}

entity plan_gist_idea {
  name : string+
  summary : string
  description : text
  disambiguation : text
}

entity plan_gist_step {
  name : string+
  summary : string
  description : text
  disambiguation : text
}

entity plan_gist_task {
  name : string+
  summary : string
  description : text
  disambiguation : text
}

entity plan_smart {
  specific_id
  measurable_id
  actionable_id
  relevant_id
  timely_id
}

entity plan_smart_specific {
  name : string+
  summary : string
  description : text
  disambiguation : text
  unit_id : unit(id)+
  value : value
}

entity plan_smart_measurable {
  name : string+
  summary : string
  description : text
  disambiguation : text
  unit_id : unit(id)+
  value : value
}

entity plan_smart_actionable {
  name : string+
  summary : string
  description : text
  disambiguation : text
  unit_id : unit(id)+
  value : value
}

entity plan_smart_relevant {
  name : string+
  summary : string
  description : text
  disambiguation : text
  unit_id : unit(id)+
  value : value
}

entity plan_smart_timely {
  name : string+
  summary : string
  description : text
  disambiguation : text
  unit_id : unit(id)+
  value : value
}

entity plan_rice {
  reach_id
  impact_id
  confidence_id
  effort_id
}

entity plan_rice_reach {
  name : string+
  summary : string
  description : text
  disambiguation : text
  unit_id : unit(id)+
  value : value
}

entity plan_rice_impact {
  name : string+
  summary : string
  description : text
  disambiguation : text
  unit_id : unit(id)+
  value : value
}

entity plan_rice_confidence {
  name : string+
  summary : string
  description : text
  disambiguation : text
  unit_id : unit(id)+
  value : value
}

entity plan_rice_effort {
  name : string+
  summary : string
  description : text
  disambiguation : text
  unit_id : unit(id)+
  value : value
}

entity plan_rope {
  realistic_id
  optimistic_id
  pessimistic_id
  equilibristic_id
}

entity plan_rope_realistic {
  name : string+
  summary : string
  description : text
  disambiguation : text
  unit_id : unit(id)+
  value : value
}

entity plan_rope_optimistic {
  name : string+
  summary : string
  description : text
  disambiguation : text
  unit_id : unit(id)+
  value : value
}

entity plan_rope_pessimistic {
  name : string+
  summary : string
  description : text
  disambiguation : text
  unit_id : unit(id)+
  value : value
}

entity plan_rope_equilibristic {
  name : string+
  summary : string
  description : text
  disambiguation : text
  unit_id : unit(id)+
  value : value
}

'''
'
' Code
'
'''

entity united_states_bureau_of_labor_statistics_standard_occupational_classification_2018 {
  group : text
  code : string
  title : string
  definition : text
}

entity international_standard_classification_occupations_2008 {
  group : text
  code : string
  title : string
  definition : text
}

entity html_color_name {
  hex : xdigit(6)
  name : string+
}

entity pantone_color {
  number : integer
  name : string+
}

@enduml
