@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity credential {
    key : string+
}

entity credential_locale {
    credential : credential(id)+
    locale : locale(id)+
    name : string+
    summary : string
    description : text
    disambiguation : text
}

credential ||-r-o{ credential_locale

@enduml
