@startuml uml
skinparam monochrome true

entity credential {
    key : string
}

entity credential_locale {
    credential : credential(id)
    locale : locale(id)
    name : string
    summary : string
    description : text
}

@enduml
