@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity plan_rice {
  reach_id : plan_item(id)+
  impact_id : plan_item(id)+
  confidence_id : plan_item(id)+
  effort_id : plan_item(id)+
}

entity plan_item {
  name : string+
  summary : string
  description : text
  disambiguation : text
  unit_id : unit(id)+
  value : value
}

@enduml
