@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity media_type {
  code : string+
  supertype : string
  subtype : string
  tree : string
  suffix  : string
  parameters : string[]
}

@enduml
