@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity system_env {
  .. Meta ..
  id : bigint ⚡
  zid : uuid ⚡
  lock_version : int
  created_at : timestamp
  created_by : url
  updated_at : timestamp
  updated_by : url
  retired_at : timestamp
  retired_by : url
  locale_id : locale.id 🔑
  .. Main ..
  key : string ⚡
  value : text
}

@enduml
