@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity sipoc {
  .. meta ..
  id : uuid ⚡
  lock_version : integer
  created_at : timestamp_utc_usec ⚡
  created_by : url ⚡
  updated_at : timestamp_utc_usec ⚡
  updated_by : url ⚡
  retired_at : timestamp_utc_usec ⚡
  retired_by : url ⚡
  locale_code : string ⚡
  tagging : string ⚡
  .. Main ..
  suppliers_as_url : url
  suppliers_as_markdown : markdown
  inputs_as_url : url
  inputs_as_markdown : markdown
  processes_as_url : url
  processes_as_markdown : markdown
  outputs_as_url : url
  outputs_as_markdown : markdown
  customers_as_url : url
  customers_as_markdown : markdown
}

@enduml
