@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity access_permission {
  .. join ..
  access_attribute_id : access_attribute.id 🔑
  access_operation_id : access_operation.id 🔑
}

@enduml
