@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity passport_credential {
  label : text
  country_text : text
  number_text : text
  valid_start_date : date
  valid_stop_date : date
}

@enduml
