@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity measurement {
  .. meta ..
  id : uuid ⚡
  lock_version : integer
  created_at : timestamp_utc_usec ⚡
  created_by : url ⚡
  updated_at : timestamp_utc_usec ⚡
  updated_by : url ⚡
  retired_at : timestamp_utc_usec ⚡
  retired_by : url ⚡
  locale_code : string ⚡
  tagging : string ⚡
  .. Main ..
  timestamp_utc_usec : timestamp_utc_usec
  measurement_unit_id : measurement_unit.id 🔑
  measurement_device_id : measurement_device.id 🔑
  value : TODO
}

@enduml
