@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity lumina_foundation_skill_level {
  .. Main ..
  number : integer ⚡
  label : string ⚡
  description : string
}

@enduml
