@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity tag {
    key : string+
}

entity tag_locale {
    tag : tag(id)+
    locale : locale(id)+
    name : string+
    summary : string
    description : text
    disambiguation : text
}

tag ||-r-o{ tag_locale

@enduml
