@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity access_agent {
  .. meta ..
  id : bigint I !
  zid : uuid I !
  lock_version : int !
  created_at : timestamp !
  created_by : url !
  updated_at : timestamp !
  updated_by : url !
  retired_at : timestamp !
  retired_by : url !
  locale_id : locale(id) K !
  .. card ..
  title : string(50) I !
  subtitle : string(50) I !
  summary : string !
  description : text !
  disambiguation : text !
  image_1024x1024_url : url !
  image_1024x1024_alt : text !
  emoji : text !
  star_count : integer !
  .. main ..
  key : string I !
}

@enduml
