@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity subcountry_code_iso_3166_2 {
  .. Main ..
  alpha_2:string(2) : string
  country_code_iso_3166_1_id : references
}

@enduml
