@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity room {
    key : string+
}

entity room_locale {
    room : room(id)+
    locale : locale(id)+
    name : string+
    summary : string
    description : text
}

room ||-r-o{ room_locale

@enduml
