@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity access_occupancy {
  .. join ..
  access_tenant_it : access_tenant.id
  access_agent_id : access_agent.id
}

@enduml
