DROP TRIGGER IF EXISTS trigger_user_ilo_isco_2008_link_updated_at;
DROP INDEX IF EXISTS user_ilo_isco_2008_link_locale_code_index;
DROP INDEX IF EXISTS user_ilo_isco_2008_link_created_at_index;
DROP INDEX IF EXISTS user_ilo_isco_2008_link_updated_at_index;
DROP INDEX IF EXISTS user_ilo_isco_2008_link_retired_at_index;
DROP INDEX IF EXISTS user_ilo_isco_2008_link_user_id_index;
DROP INDEX IF EXISTS user_ilo_isco_2008_link_ilo_isco_2008_id_index
DROP TABLE IF EXISTS user_ilo_isco_2008_link;
