@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity color_point_rgba_with_unit_interval {
  red : unit_interval
  green : unit_interval
  blue : unit_interval
  alpha : unit_interval
}

@enduml
