@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity status_system {
  .. Meta ..
  id : uuid ⚡
  sign : char ⚡
  lock_version : integer
  created_at : timestamp ⚡
  created_by : url ⚡
  updated_at : timestamp ⚡
  updated_by : url ⚡
  deleted_at : timestamp ⚡
  deleted_by : url ⚡
  locale_id : locale.id ⚡ 🔑
  .. Main ..
  key : string ⚡
  formal_name : string ⚡
}

@enduml
