@startuml uml
skinparam monochrome true

entity access_attribute {
    key : string
}

entity access_attribute_locale {
    access_attribute_id: access_attribute(id)
    locale_id: locale(id)
    name : string
    summary : string
    description : text
}

@enduml
