@startuml uml
skinparam monochrome true
skinparam linetype ortho
hide circle

entity international_standard_classification_of_occupations_2008 {
  .. Main ..
  code : string ⚡
  title : string ⚡
  definition : string
}

@enduml
