@startuml uml
skinparam monochrome true

entity access_tenant {
    key : string
}

entity access_tenant_locale {
    access_tenant: access_tenant(id)
    locale_id: locale(id)
    name : string
    summary : string
    description : text
}
